# Generated by Django 2.1.4 on 2018-12-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('sepal_length', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Sepal Length')),
                ('sepal_width', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Sepal Width')),
                ('petal_length', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Petal Length')),
                ('petal_width', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Petal Width')),
                ('species', models.CharField(max_length=30, verbose_name='Species')),
            ],
        ),
    ]
