BIT = 1
KILOBIT = 1024 * BIT
MEGABIT = 1024 * KILOBIT

BYTE = 8 * BIT
KILOBYTE = 1024 * BYTE
MEGABYTE = 1024 * KILOBYTE

print(f'1 MB in bit = {1*MEGABYTE / BIT}')
print(f'1 MB in Mb = {1*MEGABYTE / MEGABIT} Mb')
print(f'MB - Mb = {(MEGABYTE - MEGABIT) / BIT}')
