# Generated by Django 4.0.4 on 2022-05-30 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contact', '0009_alter_contact_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='group',
            field=models.ManyToManyField(blank=True, default=None, limit_choices_to={'name__startswith': 'contact'}, to='auth.group', verbose_name='Group'),
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(choices=[('+48', 'Poland'), ('+1', 'USA')], default=None, max_length=10, null=True, verbose_name='Country Code')),
                ('number', models.CharField(default=None, max_length=15, null=True, verbose_name='Phone Number')),
                ('contact', models.ForeignKey(default=None, null=None, on_delete=django.db.models.deletion.CASCADE, to='contact.contact', verbose_name='Contact')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
