# Generated by Django 4.0.4 on 2022-05-30 14:05

import contact.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_alter_contact_group_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=contact.models.upload_to, verbose_name='Image'),
        ),
    ]
