# Generated by Django 4.0.4 on 2022-05-30 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_contact_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='national_identification_number',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='National Identification Number'),
        ),
        migrations.AddField(
            model_name='contact',
            name='nationality',
            field=models.CharField(blank=True, choices=[('poland', 'Poland'), ('usa', 'USA')], default=None, max_length=30, null=True, verbose_name='Nationality'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(default=None, max_length=30, verbose_name='Street')),
                ('house_number', models.CharField(default=None, max_length=30, verbose_name='House Number')),
                ('apartment', models.CharField(default=None, max_length=30, verbose_name='Apartment')),
                ('city', models.CharField(default=None, max_length=30, verbose_name='City')),
                ('region', models.CharField(default=None, help_text='State, Voivodeship, Canton, Land, Okres', max_length=30, verbose_name='Region')),
                ('post_code', models.CharField(default=None, max_length=30, verbose_name='Post Code')),
                ('country', models.CharField(default=None, max_length=30, verbose_name='Country')),
                ('contact', models.ForeignKey(default=None, null=None, on_delete=django.db.models.deletion.CASCADE, to='contact.contact', verbose_name='Contact')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
