# Generated by Django 2.1.1 on 2018-12-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=30, verbose_name='First Name')),
                ('house_number', models.CharField(max_length=5, verbose_name='First Name')),
                ('apartment_number', models.CharField(max_length=5, verbose_name='First Name')),
                ('city', models.CharField(max_length=30, verbose_name='First Name')),
                ('post_code', models.IntegerField(verbose_name='First Name')),
                ('region', models.CharField(max_length=30, verbose_name='First Name')),
                ('country', models.CharField(max_length=30, verbose_name='First Name')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('phone', models.IntegerField(verbose_name='Phone')),
                ('date_of_birth', models.DateField(verbose_name='Date of birth')),
                ('image', models.ImageField(upload_to='person/', verbose_name='Image')),
            ],
        ),
    ]
