# Generated by Django 2.1.1 on 2018-12-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksiazkaadresowa', '0005_address_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='firends',
            field=models.ManyToManyField(blank=True, to='ksiazkaadresowa.Person', verbose_name='Friends'),
        ),
    ]
