# Generated by Django 2.1.1 on 2018-12-05 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ksiazkaadresowa', '0007_auto_20181205_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'People'},
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('first_name', 'last_name')},
        ),
    ]
