# Generated by Django 2.1.1 on 2018-12-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksiazkaadresowa', '0008_auto_20181205_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is Deleted?'),
        ),
    ]
