# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now=True, verbose_name='Datetime Add')),
                ('date_modified', models.DateTimeField(auto_now_add=True, verbose_name='Datetime Modified')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active?')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Name')),
                ('command', models.TextField(verbose_name='Command')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
            ],
        ),
    ]
