# Generated by Django 2.0.3 on 2018-03-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontakt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontakt',
            name='image',
            field=models.ImageField(default=None, upload_to='', verbose_name='Image', null=True, blank=True),
            preserve_default=False,
        ),
    ]
