# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 14:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartbeat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heartbeat',
            options={'verbose_name': 'Heartbeat', 'verbose_name_plural': 'Heartbeats'},
        ),
        migrations.AlterField(
            model_name='heartbeat',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Datetime'),
        ),
        migrations.AlterField(
            model_name='heartbeat',
            name='host',
            field=models.GenericIPAddressField(db_index=True, verbose_name='Host'),
        ),
        migrations.AlterField(
            model_name='heartbeat',
            name='port',
            field=models.PositiveIntegerField(help_text='1025-65535', validators=[django.core.validators.MinValueValidator(1025), django.core.validators.MaxValueValidator(65535)], verbose_name='Port'),
        ),
    ]
