# Generated by Django 2.2.1 on 2019-05-24 14:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeartBeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('ip', models.GenericIPAddressField(verbose_name='IP Address')),
                ('port', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1025), django.core.validators.MaxValueValidator(65535)], verbose_name='Number')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('uid', models.PositiveIntegerField(verbose_name='Unique ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP Address')),
                ('is_active', models.BooleanField(blank=True, choices=[(False, 'Inactive'), (True, 'Active'), (None, 'Unknown')], default=None, null=True, verbose_name='Is active?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1025), django.core.validators.MaxValueValidator(65535)], verbose_name='Number')),
                ('state', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('filtered', 'Filtered'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20, verbose_name='State')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.Host', verbose_name='Host')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
