# Generated by Django 2.0.6 on 2018-06-13 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_contact_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='friends',
            field=models.ManyToManyField(blank=True, default=None, to='contact.Contact', verbose_name='Friends'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='reporter',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Reporter'),
        ),
    ]
