# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0002_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='host.Group', verbose_name='Group'),
            preserve_default=False,
        ),
    ]
