# Generated by Django 4.0.4 on 2022-05-30 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='First Name')),
                ('lastname', models.CharField(db_index=True, max_length=50, verbose_name='Last Name')),
                ('born', models.DateField(blank=True, default=None, null=True, verbose_name='Birthday')),
                ('gender', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Gender')),
                ('email', models.EmailField(blank=True, default=None, max_length=100, null=True, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Phone Number')),
                ('tax_number', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Tax Number')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('billing', 'Billing'), ('shipping', 'Shipping')], default=None, max_length=50, null=True, verbose_name='Type')),
                ('street', models.CharField(blank=True, default=None, max_length=70, null=True, verbose_name='Street')),
                ('postcode', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Post Code')),
                ('city', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='City')),
                ('region', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Region')),
                ('country', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Country')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
