# Generated by Django 2.0.6 on 2018-06-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Image'),
        ),
    ]
