# Generated by Django 2.0.6 on 2018-06-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20180613_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default=None, max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(blank=True, choices=[('best-friend', 'Best Friend'), ('friend', 'Friend'), ('acquaintance', 'Acquaintance'), ('other', 'Other')], default=None, max_length=30, null=True, verbose_name='Status'),
        ),
    ]
