# Generated by Django 4.0.4 on 2022-05-30 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_contact_email_contact_is_astronaut'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='height',
            field=models.FloatField(blank=True, default=None, help_text='cm', null=True, validators=[django.core.validators.MinValueValidator(150), django.core.validators.MaxValueValidator(210)], verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='contact',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300000)], verbose_name='Salary'),
        ),
        migrations.AddField(
            model_name='contact',
            name='weight',
            field=models.FloatField(blank=True, default=None, help_text='kg', null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(90)], verbose_name='Weight'),
        ),
    ]
