# Generated by Django 4.0.4 on 2022-05-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0012_contact_national_identification_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='type',
            field=models.CharField(blank=True, choices=[('None', 'Unknown'), ('home', 'Home'), ('work', 'Work')], default='None', max_length=15, null=True, verbose_name='Type'),
        ),
    ]
