# Generated by Django 4.0.4 on 2022-05-30 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact', '0013_phone_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'default_related_name': 'contact_address'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'default_related_name': 'contact_contact'},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'default_related_name': 'contact_phone'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='add_author',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='add_date', to=settings.AUTH_USER_MODEL, verbose_name='Add Author'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='edit_author',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edit_date', to=settings.AUTH_USER_MODEL, verbose_name='Edit Author'),
        ),
    ]
