# Generated by Django 4.0.4 on 2022-05-30 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0016_rename_contact_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='contact',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='contact',
            new_name='person',
        ),
    ]
