# Generated by Django 4.0.4 on 2022-05-30 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0018_alter_address_person_alter_phone_person'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'default_related_name': 'contact_person', 'verbose_name': 'Person', 'verbose_name_plural': 'People'},
        ),
    ]
