# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='command',
            options={'verbose_name': 'Command', 'verbose_name_plural': 'Commands'},
        ),
    ]
