# Generated by Django 4.0.4 on 2022-05-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ean13', models.CharField(max_length=13, unique=True, verbose_name='Ean13')),
                ('name', models.CharField(db_index=True, max_length=13, verbose_name='Name')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Net price (without tax)', max_digits=7, null=True, verbose_name='Price')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
